//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Booking_Id { get; set; }
        public string User_Id { get; set; }
        public int Space_Id { get; set; }
        public System.DateTime Entry_date { get; set; }
        public System.DateTime Exit_date { get; set; }
        public string Description { get; set; }
    
        public virtual Space Space { get; set; }
    }
}
